### Numpy 연습문제
**필요한 모듈은 import 하여 사용합니다.**

---

In [1]:
# 이곳에 필요한 모듈 import 한 후 실행
import numpy as np
from load_utile import load_one_stock, load_dates
from load_utile import load_matrix

1. 다음 리스트 [1, 2, 3, 4, 5]를 ndarray로 변환하고, 배열의 차원(ndim)과 형태(shape)을 출력하시오.

In [3]:
list1 = [1,2,3,4,5]
arr = np.array(list1)
print(f"배열의 차원 : {arr.ndim} 형태 : {arr.shape}")

배열의 차원 : 1 형태 : (5,)


2. np.arange()를 이용해 0부터 20까지의 짝수로 이루어진 배열을 생성하시오.

In [4]:
arr = np.arange(0,21,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20]


3. 다음 제시된 리스트를 배열로 변환한 후, 3 이상인 값만 추출하는 불리언 인덱싱 코드를 작성하시오.

In [5]:
list3 = [1,3,5,2,8,3]
arr = np.array(list3)
arr[arr>= 3]

array([3, 5, 8, 3])

4. 다음 제시된 리스트를 배열로 변환한 후, 두 번째 행만 슬라이싱하여 출력하시오.

In [6]:
list4 = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
arr = np.array(list4)
print(arr[1])

[40 50 60]


5. 다음 제시된 리스트를 배열로 변환한 후, 모든 홀수에만 10을 더하는 벡터화 연산을 수행하시오.

In [7]:
list5 = [1, 2, 3, 4, 5]
arr = np.array(list5)
arr[arr %2 == 1] += 10
print(arr)

[11  2 13  4 15]


6. 다음 제시된 실수 리스트를 배열로 변환한 후, 반올림한 정수형 배열로 변환하시오.\
   주의 : astype 만 쓰면 소수점 아래가 버려져서 값이 새어나간다.

    - [출력 예시]
        - np.array([52000.9, -3.7]) -> [52001, -4]

    - [힌트] 반올림을 먼저 하고 타입을 바꾼다. 순서가 중요하다.

In [8]:
list6 = [52000.9, 51999.2, -3.7, 52000.5]
arr = np.array(list6)

result = np.round(arr).astype(int)
print(result)


[52001 51999    -4 52000]


#### == 아래 문제들은 실습용 데이터(prices.csv, load_utils.py)를 활용하여 풀이해보세요. ==

7. 첫 종목의 종가 데이터를 기준으로 최저가, 최고가와 그에 해당하는 날짜를 각각 출력하시오. \
    (실습용 데이터의 prices 와 dates 는 길이와 순서가 같다.)

    - [출력 예시]
        - (25899, numpy.datetime64('2023-10-16'), 8885, numpy.datetime64('2026-05-21'))

    - [힌트] max 는 '값', argmax 는 '그 값이 있는 위치' 다.\
            위치를 얻으면 길이가 같은 다른 배열에서 같은 자리를 꺼낼 수 있다.

In [9]:
prices = load_one_stock(0) # 첫 종목의 종가 750개
dates= load_dates()          # 날짜 750개
print(f"최고가 : {prices.max()} 날짜 : {dates[prices.argmax()]}")
print(f"최저가 : {prices.min()} 날짜 : {dates[prices.argmin()]}")

최고가 : 25899 날짜 : 2023-10-16
최저가 : 8885 날짜 : 2026-05-21


8. 종가 데이터를 기준으로 각 종목별 평균가와, 날짜별 평균가를 구하시오. 
    또한, 각 종목에서 자기 평균을 뺀 배열을 구하시오.
    
    [힌트]
    - 종목별 평균가 : (종목 수,) 배열 
    
    - 날짜별 평균가 : (날짜 수,) 배열
    
    - 각 종목에서 자기 평균을 뺀 배열 : (종목 수, 날짜 수) 배열 \
        결과의 종목별 평균은 0 이 되어야 한다.

In [10]:
matrix = load_matrix()  # (120, 750) 행 : 종목 120개 / 열: 날짜 750개
print(np.isnan(matrix).sum())   # 0
print(f"종목별 평균 : {matrix.mean(axis=1)}")
print(f"날짜별 평균 : {matrix.mean(axis=0)}")
means = matrix.mean(axis=1,keepdims=True)
result = matrix - means
print(np.allclose(result.mean(axis=1), 0))    # True

0
종목별 평균 : [ 15809.688       30689.94266667  14169.368       54451.92933333
  67169.48533333   8109.51333333  47694.38666667 125418.40266667
  21475.032       16634.44266667  10176.71333333  16543.46
  96844.08933333   6727.924       12047.256        7687.344
  49569.47066667  51635.32933333  96000.344       17587.856
  21627.556       25293.748      102137.63466667   5210.30533333
  31546.79333333  12729.256       84966.104        4142.08933333
  49008.256      136101.04133333  15043.72        45153.67866667
  10766.00266667  16581.31733333  22889.84666667  44871.83866667
   6306.00666667  45419.70933333   9956.17333333   8675.09333333
  12464.42133333 172957.71733333  22123.69866667  55023.65733333
 288927.096       70159.83866667  11006.276      168665.03733333
  74455.89866667  32674.81733333  81660.984      138736.392
  31575.56933333  64851.232       28994.80133333  20424.28666667
  23158.45066667  16078.416       36501.824       66740.
  21358.97333333   9665.45066667   9703.589